-- Deciduous MCP PostgreSQL bootstrap schema.
-- Generated by scripts/dump_structure.sh from a disposable migrated database.
-- Apply to a new, empty database only; see DEPLOY.md for the command.
-- Do not apply it to an existing database.

--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


--
-- Name: node_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.node_status AS ENUM (
    'pending',
    'active',
    'completed',
    'rejected',
    'superseded',
    'abandoned'
);


--
-- Name: node_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.node_type AS ENUM (
    'goal',
    'decision',
    'option',
    'action',
    'outcome',
    'observation',
    'revisit'
);


--
-- Name: edge_tombstone_on_delete(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.edge_tombstone_on_delete() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  stamp timestamp;
BEGIN
  IF OLD.from_change_id IS NULL OR OLD.to_change_id IS NULL THEN
    RETURN OLD;
  END IF;
  -- The column is a UTC timestamp without a zone, like every other here.
  stamp := coalesce(
    nullif(current_setting('deciduous.unlinked_at', true), '')::timestamptz,
    now()
  ) AT TIME ZONE 'UTC';
  INSERT INTO edge_tombstones (workspace_id, from_change_id, to_change_id, edge_type, deleted_at)
    VALUES (OLD.workspace_id, OLD.from_change_id, OLD.to_change_id, OLD.edge_type, stamp)
    ON CONFLICT (workspace_id, from_change_id, to_change_id, edge_type)
    DO UPDATE SET deleted_at = greatest(edge_tombstones.deleted_at, EXCLUDED.deleted_at);
  RETURN OLD;
END;
$$;


--
-- Name: edge_tombstone_on_insert(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.edge_tombstone_on_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  DELETE FROM edge_tombstones
    WHERE workspace_id = NEW.workspace_id
      AND from_change_id = NEW.from_change_id
      AND to_change_id = NEW.to_change_id
      AND edge_type = NEW.edge_type;
  RETURN NEW;
END;
$$;


--
-- Name: notify_graph_event(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.notify_graph_event() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  ws_name text;
  from_branch text;
  body jsonb;
  op text := TG_OP;
  changed text[] := ARRAY[]::text[];
  n decision_nodes%ROWTYPE;
  e decision_edges%ROWTYPE;
  new_seq bigint;
BEGIN
  IF TG_TABLE_NAME = 'decision_nodes' THEN
    n := NEW;
    IF TG_OP = 'UPDATE' AND OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN
      op := 'DELETE';
    ELSIF TG_OP = 'INSERT' AND NEW.deleted_at IS NOT NULL THEN
      op := 'DELETE';
    ELSIF TG_OP = 'UPDATE' THEN
      IF OLD.title IS DISTINCT FROM NEW.title THEN changed := array_append(changed, 'title'); END IF;
      IF OLD.status IS DISTINCT FROM NEW.status THEN changed := array_append(changed, 'status'); END IF;
      IF OLD.description IS DISTINCT FROM NEW.description THEN changed := array_append(changed, 'description'); END IF;
      IF OLD.metadata IS DISTINCT FROM NEW.metadata THEN changed := array_append(changed, 'metadata'); END IF;
      IF OLD.node_type IS DISTINCT FROM NEW.node_type THEN changed := array_append(changed, 'node_type'); END IF;
      IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN changed := array_append(changed, 'restored'); END IF;
    END IF;
    SELECT name INTO ws_name FROM workspaces WHERE id = n.workspace_id;

    body := jsonb_build_object(
      'table', 'decision_nodes',
      'op', op,
      'workspace', ws_name,
      'id', n.id,
      'change_id', n.change_id,
      'node_type', n.node_type,
      'title', left(n.title, 200),
      'status', n.status,
      'branch', left(n.metadata ->> 'branch', 200)
    );
    IF TG_OP = 'UPDATE' AND op = 'UPDATE' THEN
      body := body || jsonb_build_object('changed', to_jsonb(changed));
    END IF;
  ELSIF TG_TABLE_NAME = 'decision_edges' THEN
    IF TG_OP = 'DELETE' THEN e := OLD; ELSE e := NEW; END IF;
    SELECT name INTO ws_name FROM workspaces WHERE id = e.workspace_id;
    SELECT left(metadata ->> 'branch', 200) INTO from_branch
      FROM decision_nodes WHERE id = e.from_node_id;

    body := jsonb_build_object(
      'table', 'decision_edges',
      'op', op,
      'workspace', ws_name,
      'id', e.id,
      'edge_type', e.edge_type,
      'from_change_id', e.from_change_id,
      'to_change_id', e.to_change_id,
      'branch', from_branch
    );
  END IF;

  new_seq := nextval(pg_get_serial_sequence('graph_events', 'seq'));
  body := body || jsonb_build_object(
    'seq', new_seq,
    'at', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
  );
  INSERT INTO graph_events (seq, workspace, payload)
    VALUES (new_seq, coalesce(ws_name, ''), body);

  IF new_seq % 1000 = 0 THEN
    DELETE FROM graph_events WHERE inserted_at < (now() AT TIME ZONE 'UTC') - interval '7 days';
  END IF;

  PERFORM pg_notify('graph_events', body::text);
  RETURN NULL;
END;
$$;


SET default_table_access_method = heap;

--
-- Name: applied_ops; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.applied_ops (
    workspace_id uuid NOT NULL,
    op_id character varying(255) NOT NULL,
    kind character varying(255) NOT NULL,
    applied_at timestamp without time zone NOT NULL
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    user_id uuid,
    entity_type character varying(255) NOT NULL,
    entity_id uuid NOT NULL,
    entity_change_id character varying(255),
    action character varying(255) NOT NULL,
    changes jsonb DEFAULT '{}'::jsonb,
    source character varying(255) DEFAULT 'mcp'::character varying NOT NULL,
    inserted_at timestamp without time zone NOT NULL
);


--
-- Name: command_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.command_log (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    decision_node_id uuid,
    command text NOT NULL,
    description text,
    working_dir character varying(255),
    exit_code integer,
    stdout text,
    stderr text,
    duration_ms integer,
    started_at timestamp without time zone NOT NULL,
    completed_at timestamp without time zone,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: decision_edges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.decision_edges (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    from_node_id uuid NOT NULL,
    to_node_id uuid NOT NULL,
    from_change_id character varying(255),
    to_change_id character varying(255),
    edge_type character varying(255) DEFAULT 'leads_to'::character varying NOT NULL,
    weight double precision DEFAULT 1.0,
    rationale text,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: decision_nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.decision_nodes (
    id uuid NOT NULL,
    change_id character varying(255) NOT NULL,
    workspace_id uuid NOT NULL,
    created_by_id uuid,
    node_type character varying(255) NOT NULL,
    title text NOT NULL,
    description text,
    status character varying(255) DEFAULT 'pending'::character varying NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    deleted_at timestamp without time zone,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: document_blobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_blobs (
    content_hash character varying(64) NOT NULL,
    content bytea NOT NULL,
    byte_size bigint NOT NULL,
    mime_type character varying(255),
    inserted_at timestamp without time zone NOT NULL
);


--
-- Name: edge_tombstones; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.edge_tombstones (
    workspace_id uuid NOT NULL,
    from_change_id character varying(255) NOT NULL,
    to_change_id character varying(255) NOT NULL,
    edge_type character varying(255) NOT NULL,
    deleted_at timestamp without time zone NOT NULL
);


--
-- Name: graph_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.graph_events (
    seq bigint NOT NULL,
    workspace text NOT NULL,
    payload jsonb NOT NULL,
    inserted_at timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


--
-- Name: graph_events_seq_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.graph_events_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: graph_events_seq_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.graph_events_seq_seq OWNED BY public.graph_events.seq;


--
-- Name: node_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.node_documents (
    id uuid NOT NULL,
    change_id character varying(255) NOT NULL,
    workspace_id uuid NOT NULL,
    node_id uuid NOT NULL,
    content_hash character varying(255) NOT NULL,
    original_filename character varying(255) NOT NULL,
    storage_filename character varying(255) NOT NULL,
    mime_type character varying(255) NOT NULL,
    file_size integer NOT NULL,
    description text,
    description_source character varying(255) DEFAULT 'none'::character varying NOT NULL,
    attached_by character varying(255),
    detached_at timestamp without time zone,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    content_missing boolean DEFAULT false NOT NULL,
    storage character varying(255) DEFAULT 'postgres'::character varying NOT NULL
);


--
-- Name: node_themes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.node_themes (
    node_id uuid NOT NULL,
    theme_id uuid NOT NULL,
    source character varying(255) DEFAULT 'manual'::character varying NOT NULL,
    inserted_at timestamp without time zone NOT NULL
);


--
-- Name: qa_interactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qa_interactions (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    user_prompt text NOT NULL,
    total_prompt text NOT NULL,
    response text NOT NULL,
    context jsonb,
    deleted_at timestamp without time zone,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    search_vector tsvector GENERATED ALWAYS AS ((setweight(to_tsvector('english'::regconfig, COALESCE(user_prompt, ''::text)), 'A'::"char") || setweight(to_tsvector('english'::regconfig, COALESCE(response, ''::text)), 'B'::"char"))) STORED
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version bigint NOT NULL,
    inserted_at timestamp(0) without time zone
);


--
-- Name: themes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.themes (
    id uuid NOT NULL,
    change_id character varying(255) NOT NULL,
    workspace_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    color character varying(255) DEFAULT '#6b7280'::character varying NOT NULL,
    description text,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    workspace_id uuid NOT NULL,
    git_name character varying(255) NOT NULL,
    email character varying(255),
    display_name character varying(255),
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: workspaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workspaces (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    settings jsonb DEFAULT '{}'::jsonb,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);


--
-- Name: write_activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.write_activity (
    workspace_id uuid NOT NULL,
    branch text NOT NULL,
    session_id character varying(255) NOT NULL,
    client_name text,
    client_version text,
    first_seen_at timestamp without time zone NOT NULL,
    last_seen_at timestamp without time zone NOT NULL
);


--
-- Name: graph_events seq; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graph_events ALTER COLUMN seq SET DEFAULT nextval('public.graph_events_seq_seq'::regclass);


--
-- Name: applied_ops applied_ops_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applied_ops
    ADD CONSTRAINT applied_ops_pkey PRIMARY KEY (workspace_id, op_id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: command_log command_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_log
    ADD CONSTRAINT command_log_pkey PRIMARY KEY (id);


--
-- Name: decision_edges decision_edges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision_edges
    ADD CONSTRAINT decision_edges_pkey PRIMARY KEY (id);


--
-- Name: decision_nodes decision_nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision_nodes
    ADD CONSTRAINT decision_nodes_pkey PRIMARY KEY (id);


--
-- Name: document_blobs document_blobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_blobs
    ADD CONSTRAINT document_blobs_pkey PRIMARY KEY (content_hash);


--
-- Name: edge_tombstones edge_tombstones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.edge_tombstones
    ADD CONSTRAINT edge_tombstones_pkey PRIMARY KEY (workspace_id, from_change_id, to_change_id, edge_type);


--
-- Name: graph_events graph_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graph_events
    ADD CONSTRAINT graph_events_pkey PRIMARY KEY (seq);


--
-- Name: node_documents node_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_documents
    ADD CONSTRAINT node_documents_pkey PRIMARY KEY (id);


--
-- Name: qa_interactions qa_interactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_interactions
    ADD CONSTRAINT qa_interactions_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: themes themes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.themes
    ADD CONSTRAINT themes_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: workspaces workspaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);


--
-- Name: write_activity write_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.write_activity
    ADD CONSTRAINT write_activity_pkey PRIMARY KEY (workspace_id, branch, session_id);


--
-- Name: audit_log_entity_type_entity_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_entity_type_entity_id_index ON public.audit_log USING btree (entity_type, entity_id);


--
-- Name: audit_log_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_user_id_index ON public.audit_log USING btree (user_id);


--
-- Name: audit_log_workspace_id_inserted_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX audit_log_workspace_id_inserted_at_index ON public.audit_log USING btree (workspace_id, inserted_at);


--
-- Name: command_log_decision_node_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX command_log_decision_node_id_index ON public.command_log USING btree (decision_node_id);


--
-- Name: command_log_workspace_id_started_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX command_log_workspace_id_started_at_index ON public.command_log USING btree (workspace_id, started_at);


--
-- Name: decision_edges_from_node_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX decision_edges_from_node_id_index ON public.decision_edges USING btree (from_node_id);


--
-- Name: decision_edges_from_node_id_to_node_id_edge_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX decision_edges_from_node_id_to_node_id_edge_type_index ON public.decision_edges USING btree (from_node_id, to_node_id, edge_type);


--
-- Name: decision_edges_to_node_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX decision_edges_to_node_id_index ON public.decision_edges USING btree (to_node_id);


--
-- Name: decision_edges_workspace_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX decision_edges_workspace_id_index ON public.decision_edges USING btree (workspace_id);


--
-- Name: decision_nodes_workspace_id_change_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX decision_nodes_workspace_id_change_id_index ON public.decision_nodes USING btree (workspace_id, change_id);


--
-- Name: decision_nodes_workspace_id_inserted_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX decision_nodes_workspace_id_inserted_at_index ON public.decision_nodes USING btree (workspace_id, inserted_at);


--
-- Name: decision_nodes_workspace_id_node_type_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX decision_nodes_workspace_id_node_type_index ON public.decision_nodes USING btree (workspace_id, node_type);


--
-- Name: decision_nodes_workspace_id_status_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX decision_nodes_workspace_id_status_index ON public.decision_nodes USING btree (workspace_id, status);


--
-- Name: graph_events_workspace_seq_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX graph_events_workspace_seq_index ON public.graph_events USING btree (workspace, seq);


--
-- Name: idx_edges_ws_inserted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_edges_ws_inserted ON public.decision_edges USING btree (workspace_id, inserted_at);


--
-- Name: idx_nodes_branch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_branch ON public.decision_nodes USING btree (((metadata ->> 'branch'::text)));


--
-- Name: idx_nodes_description_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_description_trgm ON public.decision_nodes USING gin (description public.gin_trgm_ops);


--
-- Name: idx_nodes_metadata_text_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_metadata_text_trgm ON public.decision_nodes USING gin (((metadata)::text) public.gin_trgm_ops);


--
-- Name: idx_nodes_title_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_title_trgm ON public.decision_nodes USING gin (title public.gin_trgm_ops);


--
-- Name: idx_nodes_ws_branch_inserted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_ws_branch_inserted ON public.decision_nodes USING btree (workspace_id, ((metadata ->> 'branch'::text)), inserted_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_nodes_ws_branchkey_latest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_ws_branchkey_latest ON public.decision_nodes USING btree (workspace_id, COALESCE((metadata ->> 'branch'::text), ''::text), inserted_at DESC, id DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_nodes_ws_type_inserted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_nodes_ws_type_inserted ON public.decision_nodes USING btree (workspace_id, node_type, inserted_at DESC) WHERE (deleted_at IS NULL);


--
-- Name: idx_qa_search; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_qa_search ON public.qa_interactions USING gin (search_vector);


--
-- Name: node_documents_content_hash_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX node_documents_content_hash_index ON public.node_documents USING btree (content_hash);


--
-- Name: node_documents_content_missing_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX node_documents_content_missing_index ON public.node_documents USING btree (content_missing);


--
-- Name: node_documents_detached_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX node_documents_detached_at_index ON public.node_documents USING btree (detached_at);


--
-- Name: node_documents_node_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX node_documents_node_id_index ON public.node_documents USING btree (node_id);


--
-- Name: node_documents_workspace_id_change_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX node_documents_workspace_id_change_id_index ON public.node_documents USING btree (workspace_id, change_id);


--
-- Name: node_themes_node_id_theme_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX node_themes_node_id_theme_id_index ON public.node_themes USING btree (node_id, theme_id);


--
-- Name: node_themes_theme_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX node_themes_theme_id_index ON public.node_themes USING btree (theme_id);


--
-- Name: qa_interactions_deleted_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX qa_interactions_deleted_at_index ON public.qa_interactions USING btree (deleted_at);


--
-- Name: qa_interactions_workspace_id_inserted_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX qa_interactions_workspace_id_inserted_at_index ON public.qa_interactions USING btree (workspace_id, inserted_at);


--
-- Name: themes_workspace_id_change_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX themes_workspace_id_change_id_index ON public.themes USING btree (workspace_id, change_id);


--
-- Name: themes_workspace_id_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX themes_workspace_id_name_index ON public.themes USING btree (workspace_id, name);


--
-- Name: users_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_email_index ON public.users USING btree (email);


--
-- Name: users_workspace_id_git_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_workspace_id_git_name_index ON public.users USING btree (workspace_id, git_name);


--
-- Name: users_workspace_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_workspace_id_index ON public.users USING btree (workspace_id);


--
-- Name: workspaces_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX workspaces_name_index ON public.workspaces USING btree (name);


--
-- Name: write_activity_workspace_id_last_seen_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX write_activity_workspace_id_last_seen_at_index ON public.write_activity USING btree (workspace_id, last_seen_at);


--
-- Name: decision_edges decision_edges_notify_delete; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER decision_edges_notify_delete AFTER DELETE ON public.decision_edges FOR EACH ROW EXECUTE FUNCTION public.notify_graph_event();


--
-- Name: decision_edges decision_edges_notify_insert; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER decision_edges_notify_insert AFTER INSERT ON public.decision_edges FOR EACH ROW EXECUTE FUNCTION public.notify_graph_event();


--
-- Name: decision_edges decision_edges_notify_update; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER decision_edges_notify_update AFTER UPDATE ON public.decision_edges FOR EACH ROW WHEN ((old.* IS DISTINCT FROM new.*)) EXECUTE FUNCTION public.notify_graph_event();


--
-- Name: decision_edges decision_edges_tombstone_delete; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER decision_edges_tombstone_delete AFTER DELETE ON public.decision_edges FOR EACH ROW EXECUTE FUNCTION public.edge_tombstone_on_delete();


--
-- Name: decision_edges decision_edges_tombstone_insert; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER decision_edges_tombstone_insert AFTER INSERT ON public.decision_edges FOR EACH ROW EXECUTE FUNCTION public.edge_tombstone_on_insert();


--
-- Name: decision_nodes decision_nodes_notify_insert; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER decision_nodes_notify_insert AFTER INSERT ON public.decision_nodes FOR EACH ROW EXECUTE FUNCTION public.notify_graph_event();


--
-- Name: decision_nodes decision_nodes_notify_update; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER decision_nodes_notify_update AFTER UPDATE ON public.decision_nodes FOR EACH ROW WHEN ((old.* IS DISTINCT FROM new.*)) EXECUTE FUNCTION public.notify_graph_event();


--
-- Name: applied_ops applied_ops_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applied_ops
    ADD CONSTRAINT applied_ops_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: audit_log audit_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: audit_log audit_log_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: command_log command_log_decision_node_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_log
    ADD CONSTRAINT command_log_decision_node_id_fkey FOREIGN KEY (decision_node_id) REFERENCES public.decision_nodes(id) ON DELETE SET NULL;


--
-- Name: command_log command_log_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.command_log
    ADD CONSTRAINT command_log_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: decision_edges decision_edges_from_node_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision_edges
    ADD CONSTRAINT decision_edges_from_node_id_fkey FOREIGN KEY (from_node_id) REFERENCES public.decision_nodes(id) ON DELETE CASCADE;


--
-- Name: decision_edges decision_edges_to_node_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision_edges
    ADD CONSTRAINT decision_edges_to_node_id_fkey FOREIGN KEY (to_node_id) REFERENCES public.decision_nodes(id) ON DELETE CASCADE;


--
-- Name: decision_edges decision_edges_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision_edges
    ADD CONSTRAINT decision_edges_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: decision_nodes decision_nodes_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision_nodes
    ADD CONSTRAINT decision_nodes_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: decision_nodes decision_nodes_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision_nodes
    ADD CONSTRAINT decision_nodes_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: edge_tombstones edge_tombstones_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.edge_tombstones
    ADD CONSTRAINT edge_tombstones_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: node_documents node_documents_node_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_documents
    ADD CONSTRAINT node_documents_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.decision_nodes(id) ON DELETE CASCADE;


--
-- Name: node_documents node_documents_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_documents
    ADD CONSTRAINT node_documents_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: node_themes node_themes_node_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_themes
    ADD CONSTRAINT node_themes_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.decision_nodes(id) ON DELETE CASCADE;


--
-- Name: node_themes node_themes_theme_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.node_themes
    ADD CONSTRAINT node_themes_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.themes(id) ON DELETE CASCADE;


--
-- Name: qa_interactions qa_interactions_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qa_interactions
    ADD CONSTRAINT qa_interactions_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: themes themes_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.themes
    ADD CONSTRAINT themes_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: users users_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- Name: write_activity write_locks_workspace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.write_activity
    ADD CONSTRAINT write_locks_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


-- Ecto migration ledger ------------------------------------------------------
-- This marks the snapshot migrations as applied so a later container release
-- only runs migrations introduced after this schema version.
INSERT INTO public.schema_migrations (version, inserted_at) VALUES
  (20260301000001, NOW()),
  (20260301000002, NOW()),
  (20260301000003, NOW()),
  (20260301000004, NOW()),
  (20260301000005, NOW()),
  (20260301000006, NOW()),
  (20260301000007, NOW()),
  (20260301000008, NOW()),
  (20260301000009, NOW()),
  (20260921000001, NOW()),
  (20260921000002, NOW()),
  (20260922000001, NOW()),
  (20260922010000, NOW()),
  (20260922120000, NOW()),
  (20260922130000, NOW()),
  (20260922200000, NOW()),
  (20260922200100, NOW()),
  (20260923010000, NOW()),
  (20260923120000, NOW()),
  (20260924010000, NOW()),
  (20260924020000, NOW()),
  (20260924100000, NOW()),
  (20260924110000, NOW());

-- Database defaults from the migrated database -------------------------------
DO $$
BEGIN
  EXECUTE format('ALTER DATABASE %I SET %I = %L', current_database(), 'random_page_cost', '1.1');
  EXECUTE format('ALTER DATABASE %I SET %I = %L', current_database(), 'work_mem', '16MB');
END
$$;
