#!/usr/bin/env bash
# Regenerate STRUCTURE.sql from a fully migrated PostgreSQL database.
#
# Usage:
#   DATABASE_URL=ecto://USER:PASS@HOST/deciduous_schema_check ./scripts/dump_structure.sh
#   PGHOST=postgres PGDATABASE=schema_check PGUSER=postgres ./scripts/dump_structure.sh
#
# Use the disposable database from test/release, never a production database.
# Review and commit the snapshot with its migrations. Only schema and migration
# versions are exported; migration timestamps and application data are excluded.
set -euo pipefail

project_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${1:-$project_dir/STRUCTURE.sql}"

if [ -n "${DATABASE_URL:-}" ]; then
  case "$DATABASE_URL" in
    ecto://*) export PGDATABASE="postgres:${DATABASE_URL#ecto:}" ;;
    postgres://* | postgresql://*) export PGDATABASE="$DATABASE_URL" ;;
    *)
      printf '%s\n' 'DATABASE_URL must use ecto://, postgres://, or postgresql://.' >&2
      exit 1
      ;;
  esac
elif [ -z "${PGHOST:-}" ] || [ -z "${PGDATABASE:-}" ]; then
  printf '%s\n' 'Set DATABASE_URL, or both PGHOST and PGDATABASE, for the disposable migrated database.' >&2
  exit 1
fi

command -v pg_dump >/dev/null || {
  printf '%s\n' 'pg_dump is required to generate STRUCTURE.sql.' >&2
  exit 1
}

command -v psql >/dev/null || {
  printf '%s\n' 'psql is required to read the Ecto migration ledger.' >&2
  exit 1
}

structure_work="$(mktemp -d "${TMPDIR:-/tmp}/deciduous-mcp-structure.XXXXXX")"
trap 'rm -f "$structure_work/expected" "$structure_work/actual" "$structure_work/schema" "$structure_work/settings"; rmdir "$structure_work"' EXIT

for migration in "$project_dir"/priv/repo/migrations/[0-9]*_*.exs; do
  filename="${migration##*/}"
  printf '%s\n' "${filename%%_*}"
done | LC_ALL=C sort > "$structure_work/expected"

psql -X --no-password -v ON_ERROR_STOP=1 -Atc \
  'SELECT version FROM public.schema_migrations ORDER BY version' > "$structure_work/actual"

if ! diff -u "$structure_work/expected" "$structure_work/actual"; then
  printf '%s\n' 'Migration ledger differs from this checkout. Fully migrate a disposable database before generating STRUCTURE.sql.' >&2
  exit 1
fi

# Database settings are not part of a schema-only pg_dump. Read the defaults
# actually set by migrations instead of maintaining a second hardcoded list.
# Reject custom GUCs so application settings (which could contain secrets) can
# never be copied into a release artifact.
psql -X --no-password -v ON_ERROR_STOP=1 --quiet <<'SQL'
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_db_role_setting d, unnest(d.setconfig) AS entry(setting)
    WHERE d.setdatabase = (SELECT oid FROM pg_database WHERE datname = current_database())
      AND d.setrole = 0
      AND NOT EXISTS (SELECT 1 FROM pg_settings WHERE name = split_part(entry.setting, '=', 1))
  ) THEN
    RAISE EXCEPTION 'Custom database settings cannot be exported into STRUCTURE.sql';
  END IF;
END
$$;
SQL

psql -X --no-password -v ON_ERROR_STOP=1 -Atc "
  SELECT format('  EXECUTE format(''ALTER DATABASE %%I SET %%I = %%L'', current_database(), %L, %L);',
                split_part(entry.setting, '=', 1), substr(entry.setting, strpos(entry.setting, '=') + 1))
  FROM pg_db_role_setting d, unnest(d.setconfig) AS entry(setting)
  WHERE d.setdatabase = (SELECT oid FROM pg_database WHERE datname = current_database())
    AND d.setrole = 0
  ORDER BY entry.setting" > "$structure_work/settings"

{
  printf '%s\n' '-- Deciduous MCP PostgreSQL bootstrap schema.'
  printf '%s\n' '-- Generated by scripts/dump_structure.sh from a disposable migrated database.'
  printf '%s\n' '-- Apply to a new, empty database only; see DEPLOY.md for the command.'
  printf '%s\n' '-- Do not apply it to an existing database.'
  printf '\n'

  # Version banners and random psql guard tokens change across patch releases.
  # The source is a disposable database built from this repository's migrations.
  pg_dump --no-password --schema-only --no-owner --no-privileges --no-tablespaces |
    sed '/^\\restrict /d; /^\\unrestrict /d; /^-- Dumped from database version /d; /^-- Dumped by pg_dump version /d; /^SET transaction_timeout = 0;$/d'

  printf '%s' '-- Ecto migration ledger ------------------------------------------------------'
  printf '\n'
  printf '%s\n' '-- This marks the snapshot migrations as applied so a later container release'
  printf '%s\n' '-- only runs migrations introduced after this schema version.'
  printf '%s\n' 'INSERT INTO public.schema_migrations (version, inserted_at) VALUES'

  first=1
  while IFS= read -r version; do
    case "$version" in
      '' | *[!0-9]*)
        printf 'Invalid schema_migrations version: %s\n' "$version" >&2
        exit 1
        ;;
    esac

    if [ "$first" -eq 0 ]; then
      printf ',\n'
    fi

    printf '  (%s, NOW())' "$version"
    first=0
  done < "$structure_work/actual"
  printf ';\n'

  if [ -s "$structure_work/settings" ]; then
    printf '\n-- Database defaults from the migrated database -------------------------------\n'
    printf '%s\n' 'DO $$' 'BEGIN'
    cat "$structure_work/settings"
    printf '%s\n' 'END' '$$;'
  fi
} > "$structure_work/schema"

cp "$structure_work/schema" "$output"

printf 'Wrote %s\n' "$output"
