#!/usr/bin/env bash
# Test the exact downloadable Docker bundle with disposable services and data.
set -euo pipefail

project_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
test_id="deciduous-setup-$(date +%s)-$$"
test_dir="$(mktemp -d "${TMPDIR:-/tmp}/deciduous-setup.XXXXXX")"
bundle_parent="$test_dir/extracted release with spaces"
bundle="$bundle_parent/deciduous-mcp-docker"
settings="$bundle/.env"
external_settings="$test_dir/external.env"
state_volume="$test_id-state"
image="${SETUP_IMAGE:-deciduous-release-setup:test}"
client_image="${CLIENT_IMAGE:-python:3.12-slim}"
state_created=0
setup_started=0

if docker compose version >/dev/null 2>&1; then
  compose_command=(docker compose)
else
  compose_command=(docker-compose)
fi

compose_local() {
  "${compose_command[@]}" --project-name "$test_id" --env-file "$settings" \
    -f "$bundle/compose.yaml" -f "$bundle/compose.local.yaml" "$@"
}

cleanup() {
  result=$?
  trap - EXIT
  if [ "$setup_started" -eq 1 ] && [ -f "$settings" ]; then
    if [ "$result" -ne 0 ]; then
      compose_local logs --tail=60 >&2 || true
    fi
    # The exact project name and volume were generated by this invocation.
    compose_local down --volumes --remove-orphans >/dev/null 2>&1 || true
  fi
  if [ "$state_created" -eq 1 ]; then
    docker volume rm "$state_volume" >/dev/null 2>&1 || true
  fi
  case "$test_dir" in */deciduous-setup.*) rm -rf -- "$test_dir" ;; esac
  exit "$result"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

docker info >/dev/null
"$project_dir/scripts/test_setup.sh"
"$project_dir/scripts/package-docker.sh" "$test_dir/deciduous-mcp-docker.tar.gz" >/dev/null
mkdir "$bundle_parent"
tar -xzf "$test_dir/deciduous-mcp-docker.tar.gz" -C "$bundle_parent"
test -x "$bundle/scripts/setup.sh"
test ! -e "$settings"
test ! -e "$bundle/deps"
test ! -e "$bundle/_build"
test ! -e "$bundle/certs/postgres-ca.pem"
docker volume create "$state_volume" >/dev/null
state_created=1

printf '%s\n' 'Extracted bundle: install from an archive path containing spaces, with no host BEAM...'
setup_started=1
(
  unset DATABASE_URL DECIDUOUS_MCP_TOKEN POSTGRES_PASSWORD DECIDUOUS_ENV_FILE
  unset DB_SSL DB_SSL_VERIFY DB_SSL_CA_FILE POOL_SIZE DECIDUOUS_BIND_ADDRESS
  COMPOSE_PROJECT_NAME="$test_id" DECIDUOUS_PORT=0 DECIDUOUS_IMAGE="$image" \
    "$bundle/scripts/setup.sh"
)
cp "$settings" "$test_dir/settings-before.env"
test "$(find "$settings" -perm 600 | wc -l | tr -d ' ')" = 1
token="$(sed -n "s/^DECIDUOUS_MCP_TOKEN='\(.*\)'$/\1/p" "$settings")"
database_url="$(sed -n "s/^DATABASE_URL='\(.*\)'$/\1/p" "$settings")"
test "${#token}" -eq 64
test -n "$database_url"
db_before="$(compose_local ps -q db)"
test -n "$db_before"
volume_before="$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/var/lib/postgresql/data"}}{{.Name}}{{end}}{{end}}' "$db_before")"
test "$volume_before" = "${test_id}_postgres-data"

client() {
  docker run --rm --network "${test_id}_default" \
    -e SERVER_URL=http://server:4000 -e DECIDUOUS_MCP_TOKEN="$token" \
    -v "$project_dir/test/release:/tests:ro" -v "$state_volume:/state" \
    "$client_image" python /tests/acceptance.py "$@"
}
client seed --case setup-fresh
client verify --case setup-fresh
printf '%s\n' 'PASS extracted bundle: fresh PostgreSQL, migrations, private settings, authenticated MCP and document storage.'

printf '%s\n' 'Repeat setup: preserve settings, database container, volume, and existing graph...'
DECIDUOUS_IMAGE="$image" "$bundle/scripts/setup.sh"
cmp "$test_dir/settings-before.env" "$settings"
test "$(compose_local ps -q db)" = "$db_before"
test "$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/var/lib/postgresql/data"}}{{.Name}}{{end}}{{end}}' "$db_before")" = "$volume_before"
compose_local restart server >/dev/null
client wait
client verify --case setup-fresh --replaced
printf '%s\n' 'PASS repeat setup: credentials unchanged byte-for-byte; graph, document, and persistent volume survived restart.'

printf '%s\n' 'External database setup: reconnect to the existing PostgreSQL service without managing it...'
(
  unset DB_SSL DB_SSL_VERIFY DB_SSL_CA_FILE POOL_SIZE DECIDUOUS_BIND_ADDRESS
  DATABASE_URL="$database_url" DECIDUOUS_MCP_TOKEN="$token" \
    COMPOSE_PROJECT_NAME="$test_id" DECIDUOUS_PORT=0 DECIDUOUS_IMAGE="$image" \
    DECIDUOUS_ENV_FILE="$external_settings" "$bundle/scripts/setup.sh" --external-database
)
test "$(compose_local ps -q db)" = "$db_before"
test "$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/var/lib/postgresql/data"}}{{.Name}}{{end}}{{end}}' "$db_before")" = "$volume_before"
grep -q '^DECIDUOUS_DATABASE_MODE=external$' "$external_settings"
test "$(sed -n "s/^DECIDUOUS_MCP_TOKEN='\(.*\)'$/\1/p" "$external_settings")" = "$token"
client verify --case setup-fresh
client seed --case setup-external
client verify --case setup-external
cp "$external_settings" "$test_dir/external-before.env"
DECIDUOUS_IMAGE="$image" DECIDUOUS_ENV_FILE="$external_settings" "$bundle/scripts/setup.sh"
cmp "$test_dir/external-before.env" "$external_settings"
test "$(compose_local ps -q db)" = "$db_before"
client verify --case setup-external
printf '%s\n' 'PASS external setup: original PostgreSQL container and data retained; token preserved; fresh writes and repeat setup passed.'
