//! Git Guard configuration parsing
//!
//! Loads and parses `.deciduous/git-guard.toml`

use serde::Deserialize;
use std::fs;
use std::path::Path;

/// Main configuration structure
#[derive(Debug, Deserialize, Default)]
pub struct GitGuardConfig {
    #[serde(default)]
    pub general: GeneralConfig,

    #[serde(default)]
    pub banned: BannedConfig,

    #[serde(default)]
    pub rebase: RebaseConfig,

    #[serde(default)]
    pub sensitive_files: SensitiveFilesConfig,

    #[serde(default)]
    pub commit_message: CommitMessageConfig,

    #[serde(default)]
    pub protected_branches: ProtectedBranchesConfig,

    #[serde(default)]
    pub logging: LoggingConfig,
}

#[derive(Debug, Deserialize)]
pub struct GeneralConfig {
    #[serde(default = "default_true")]
    pub enabled: bool,

    #[serde(default = "default_log_file")]
    pub log_file: String,
}

impl Default for GeneralConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            log_file: "git.log".to_string(),
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct BannedConfig {
    #[serde(default = "default_banned_commands")]
    pub commands: Vec<String>,

    #[serde(default = "default_block_message")]
    pub block_message: String,
}

impl Default for BannedConfig {
    fn default() -> Self {
        Self {
            commands: default_banned_commands(),
            block_message: default_block_message(),
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct RebaseConfig {
    #[serde(default = "default_true")]
    pub blocked: bool,

    #[serde(default = "default_rebase_guidance")]
    pub guidance_message: String,
}

impl Default for RebaseConfig {
    fn default() -> Self {
        Self {
            blocked: true,
            guidance_message: default_rebase_guidance(),
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct SensitiveFilesConfig {
    #[serde(default = "default_sensitive_patterns")]
    pub patterns: Vec<String>,

    #[serde(default = "default_sensitive_block_message")]
    pub block_message: String,
}

impl Default for SensitiveFilesConfig {
    fn default() -> Self {
        Self {
            patterns: default_sensitive_patterns(),
            block_message: default_sensitive_block_message(),
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct CommitMessageConfig {
    #[serde(default = "default_true")]
    pub block_ai_attribution: bool,

    #[serde(default = "default_ai_attribution_patterns")]
    pub ai_attribution_patterns: Vec<String>,

    #[serde(default = "default_min_length")]
    pub min_length: usize,
}

impl Default for CommitMessageConfig {
    fn default() -> Self {
        Self {
            block_ai_attribution: true,
            ai_attribution_patterns: vec![
                "Generated with Claude".to_string(),
                "Co-Authored-By: Claude".to_string(),
                "Generated by AI".to_string(),
                "Claude Code".to_string(),
                "Anthropic".to_string(),
            ],
            min_length: 10,
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct ProtectedBranchesConfig {
    #[serde(default = "default_protected_branches")]
    pub names: Vec<String>,

    #[serde(default = "default_on_push")]
    pub on_push: String,

    #[serde(default)]
    pub allow_force_push: bool,
}

impl Default for ProtectedBranchesConfig {
    fn default() -> Self {
        Self {
            names: default_protected_branches(),
            on_push: "allow".to_string(),
            allow_force_push: false,
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct LoggingConfig {
    #[serde(default = "default_true")]
    pub log_all_commands: bool,

    #[serde(default = "default_log_file")]
    pub log_file: String,

    #[serde(default = "default_log_format")]
    pub format: String,
}

impl Default for LoggingConfig {
    fn default() -> Self {
        Self {
            log_all_commands: true,
            log_file: "git.log".to_string(),
            format: "{timestamp} | {status} | {command}".to_string(),
        }
    }
}

// Default value functions for serde
fn default_true() -> bool {
    true
}

fn default_log_file() -> String {
    "git.log".to_string()
}

fn default_block_message() -> String {
    "🛑 BLOCKED by Git Guard\n\nThis command is on the banned list.".to_string()
}

fn default_banned_commands() -> Vec<String> {
    vec![
        // Destructive operations
        "git reset --hard".to_string(),
        "git clean -fd".to_string(),
        "git clean -f ".to_string(),
        "rm -rf .git".to_string(),
        // Force push to protected branches
        "git push --force origin main".to_string(),
        "git push --force origin master".to_string(),
        "git push -f origin main".to_string(),
        "git push -f origin master".to_string(),
        "git push origin +main".to_string(),
        "git push origin +master".to_string(),
        // Hard branch deletion
        "git branch -D".to_string(),
        // All rebase operations
        "git rebase".to_string(),
    ]
}

fn default_sensitive_patterns() -> Vec<String> {
    vec![
        ".env".to_string(),
        ".env.*".to_string(),
        "*.pem".to_string(),
        "*.key".to_string(),
        "*.p12".to_string(),
        "*.pfx".to_string(),
        "credentials.*".to_string(),
        "secrets.*".to_string(),
        "*_rsa".to_string(),
        "*_ecdsa".to_string(),
        "*_ed25519".to_string(),
        "id_rsa".to_string(),
        "*.secret".to_string(),
        "token.txt".to_string(),
        "api_key".to_string(),
    ]
}

fn default_ai_attribution_patterns() -> Vec<String> {
    vec![
        "Generated with Claude".to_string(),
        "Co-Authored-By: Claude".to_string(),
        "Generated by AI".to_string(),
        "Claude Code".to_string(),
        "Anthropic".to_string(),
    ]
}

fn default_rebase_guidance() -> String {
    r#"🔄 REBASE BLOCKED - Manual Steps Required

Rebase rewrites commit history and can cause data loss.
Follow these steps manually:

1. CREATE BACKUP BRANCH:
   git branch backup-$(date +%Y%m%d-%H%M%S)

2. RUN REBASE MANUALLY:
   git rebase <target-branch>

3. VERIFY RESULT:
   git log --oneline -10

The backup branch preserves your original state if anything goes wrong."#
        .to_string()
}

fn default_sensitive_block_message() -> String {
    "🔐 BLOCKED: Sensitive file detected\n\nAdd these files to .gitignore instead.".to_string()
}

fn default_min_length() -> usize {
    10
}

fn default_protected_branches() -> Vec<String> {
    vec!["main".to_string(), "master".to_string()]
}

fn default_on_push() -> String {
    "allow".to_string()
}

fn default_log_format() -> String {
    "{timestamp} | {status} | {command}".to_string()
}

impl GitGuardConfig {
    /// Load configuration from `.deciduous/git-guard.toml`
    ///
    /// Returns default config if file doesn't exist.
    pub fn load() -> Result<Self, String> {
        Self::load_from_path(".deciduous/git-guard.toml")
    }

    /// Load configuration from a specific path
    pub fn load_from_path<P: AsRef<Path>>(path: P) -> Result<Self, String> {
        let path = path.as_ref();

        if !path.exists() {
            // Return default config if file doesn't exist
            return Ok(Self::default());
        }

        let contents =
            fs::read_to_string(path).map_err(|e| format!("Failed to read config: {}", e))?;

        toml::from_str(&contents).map_err(|e| format!("Failed to parse config: {}", e))
    }

    /// Check if git-guard is enabled
    pub fn is_enabled(&self) -> bool {
        self.general.enabled
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = GitGuardConfig::default();
        assert!(config.general.enabled);
        assert!(config.rebase.blocked);
        assert!(config.commit_message.block_ai_attribution);
    }

    #[test]
    fn test_parse_config() {
        let toml = r#"
[general]
enabled = true
log_file = "custom.log"

[banned]
commands = ["git reset --hard", "git push --force"]

[rebase]
blocked = true
"#;
        let config: GitGuardConfig = toml::from_str(toml).unwrap();
        assert!(config.general.enabled);
        assert_eq!(config.general.log_file, "custom.log");
        assert_eq!(config.banned.commands.len(), 2);
        assert!(config.rebase.blocked);
    }
}
