//! Git Guard - Runtime-enforced git safety rules
//!
//! Provides command-line git safety enforcement for Claude Code.
//!
//! ## Architecture
//!
//! 1. AI tool hooks call `deciduous git-guard check` before executing commands
//! 2. Git native hooks call `deciduous git-guard hook <type>` for pre-commit/push/rebase
//! 3. All logic lives in Rust - shell scripts are thin wrappers
//!
//! ## Usage
//!
//! ```bash
//! # Check a command (used by AI tool hooks)
//! deciduous git-guard check "git push --force origin main"
//! deciduous git-guard check --claude-mode  # reads JSON from stdin
//!
//! # Handle git hooks
//! deciduous git-guard hook pre-commit
//! deciduous git-guard hook pre-push
//! deciduous git-guard hook pre-rebase
//!
//! # Management
//! deciduous git-guard status
//! deciduous git-guard init
//! ```

mod check;
mod config;
mod hooks;
mod logging;
mod rules;

pub use check::{check_command, format_claude_response, CheckMode, CheckResult};
pub use config::GitGuardConfig;
pub use hooks::{check_commit_message, handle_hook, HookType};
pub use logging::log_command;
pub use rules::{contains_ai_attribution, find_sensitive_files, is_message_too_short, matches_banned};

/// Default git-guard.toml configuration
pub const DEFAULT_CONFIG: &str = r#"# Git Guard Configuration
# Runtime-enforced git safety rules

[general]
enabled = true
log_file = "git.log"

# ─────────────────────────────────────────────────────────────
# BANNED COMMANDS - Always blocked, no exceptions
# ─────────────────────────────────────────────────────────────
[banned]
commands = [
    # Destructive operations
    "git reset --hard",
    "git clean -fd",
    "git clean -f ",
    "rm -rf .git",

    # Force push to protected branches
    "git push --force origin main",
    "git push --force origin master",
    "git push -f origin main",
    "git push -f origin master",
    "git push origin +main",
    "git push origin +master",

    # Hard branch deletion
    "git branch -D",

    # ALL rebase operations (guided manually instead)
    "git rebase",
]

block_message = """
🛑 BLOCKED by Git Guard

This command is on the banned list.
For rebase operations, see the guidance below.
For other operations, ask the user to run manually with appropriate safeguards.
"""

# ─────────────────────────────────────────────────────────────
# REBASE GUIDANCE - Shown when rebase is blocked
# ─────────────────────────────────────────────────────────────
[rebase]
blocked = true
guidance_message = """
🔄 REBASE BLOCKED - Manual Steps Required

Rebase rewrites commit history and can cause data loss.
Follow these steps manually:

1. CREATE BACKUP BRANCH:
   git branch backup-$(date +%Y%m%d-%H%M%S)

2. VERIFY YOU'RE ON THE RIGHT BRANCH:
   git branch --show-current
   git log --oneline -5

3. RUN REBASE MANUALLY:
   git rebase <target-branch>

4. IF CONFLICTS OCCUR:
   - Resolve conflicts
   - git add <resolved-files>
   - git rebase --continue
   - OR: git rebase --abort to cancel

5. VERIFY RESULT:
   git log --oneline -10
   git diff backup-<timestamp>..HEAD

6. IF PUSHING TO SHARED BRANCH:
   ⚠️  Force push required: git push --force-with-lease origin <branch>
   This will overwrite remote history!

The backup branch preserves your original state if anything goes wrong.
"""

# ─────────────────────────────────────────────────────────────
# SENSITIVE FILES - Never allow committing these
# ─────────────────────────────────────────────────────────────
[sensitive_files]
patterns = [
    ".env",
    ".env.*",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
    "credentials.*",
    "secrets.*",
    "*_rsa",
    "*_ecdsa",
    "*_ed25519",
    "id_rsa",
    "*.secret",
    "token.txt",
    "api_key",
]

block_message = """
🔐 BLOCKED: Sensitive file detected

The following files appear to contain secrets:
{files}

Add them to .gitignore instead.
If you're certain this is safe, add an exception in .deciduous/git-guard.toml
"""

# ─────────────────────────────────────────────────────────────
# COMMIT MESSAGE RULES
# ─────────────────────────────────────────────────────────────
[commit_message]
block_ai_attribution = true
ai_attribution_patterns = [
    "Generated with Claude",
    "Co-Authored-By: Claude",
    "Generated by AI",
    "Claude Code",
    "Anthropic",
]
min_length = 10

# ─────────────────────────────────────────────────────────────
# PROTECTED BRANCHES
# ─────────────────────────────────────────────────────────────
[protected_branches]
names = ["main", "master", "production"]
on_push = "allow"
allow_force_push = false

# ─────────────────────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────────────────────
[logging]
log_all_commands = true
log_file = "git.log"
format = "{timestamp} | {status} | {command}"
"#;

/// Git hook script template for pre-commit
pub const PRE_COMMIT_HOOK: &str = r#"#!/bin/sh
# Git Guard pre-commit hook
# Calls deciduous binary for all logic

exec deciduous git-guard hook pre-commit
"#;

/// Git hook script template for pre-push
pub const PRE_PUSH_HOOK: &str = r#"#!/bin/sh
# Git Guard pre-push hook

exec deciduous git-guard hook pre-push "$@"
"#;

/// Git hook script template for pre-rebase
pub const PRE_REBASE_HOOK: &str = r#"#!/bin/sh
# Git Guard pre-rebase hook
# BLOCKS ALL REBASES - guides user through manual process

exec deciduous git-guard hook pre-rebase "$@"
"#;
