// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Checkbox state enum for type safety
 */
export type CheckboxState = "None" | "Unchecked" | "Checked";
