// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable command log entry
 */
export type CommandLog = { id: number, command: string, description: string | null, working_dir: string | null, exit_code: number | null, stdout: string | null, stderr: string | null, started_at: string, completed_at: string | null, duration_ms: number | null, decision_node_id: number | null, };
