// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable session
 */
export type DecisionSession = { id: number, name: string | null, started_at: string, ended_at: string | null, root_node_id: number | null, summary: string | null, };
