// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisionNode = { id: number, change_id: string, node_type: string, title: string, description: string | null, status: string, created_at: string, updated_at: string, metadata_json: string | null, };
