// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable decision context
 */
export type DecisionContext = { id: number, node_id: number, context_type: string, content_json: string, captured_at: string, };
