// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable decision edge
 */
export type DecisionEdge = { id: number, from_node_id: number, to_node_id: number, from_change_id: string | null, to_change_id: string | null, edge_type: string, weight: number | null, rationale: string | null, created_at: string, };
