// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable GitHub issue cache entry
 */
export type GitHubIssueCache = { id: number, issue_number: number, repo: string, title: string, body: string | null, state: string, html_url: string, created_at: string, updated_at: string, cached_at: string, };
