// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable node-theme association
 */
export type NodeTheme = { node_id: number, theme_id: number, source: string, created_at: string, };
