// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable node document attachment
 */
export type NodeDocument = { id: number, change_id: string, node_id: number, node_change_id: string, content_hash: string, original_filename: string, storage_filename: string, mime_type: string, file_size: number, description: string | null, description_source: string, attached_at: string, attached_by: string | null, detached_at: string | null, };
