// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable Q&A interaction
 */
export type QaInteraction = { id: number, user_prompt: string, total_prompt: string, response: string, context_json: string | null, inserted_at: string, deleted_at: string | null, };
