// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QaInteraction } from "./QaInteraction";

/**
 * Q&A search result with FTS5 ranking and highlighted snippets
 */
export type QaSearchResult = { interaction: QaInteraction, rank: number, snippet_prompt: string, snippet_response: string, };
