// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable roadmap sync state
 */
export type RoadmapSyncState = { id: number, roadmap_path: string, roadmap_content_hash: string | null, github_repo: string | null, last_github_sync: string | null, last_markdown_parse: string | null, conflict_count: number, };
