// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable roadmap conflict
 */
export type RoadmapConflict = { id: number, item_change_id: string, conflict_type: string, local_value: string | null, remote_value: string | null, resolution: string | null, detected_at: string, resolved_at: string | null, };
