// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queryable roadmap item
 */
export type RoadmapItem = { id: number, change_id: string, title: string, description: string | null, section: string | null, parent_id: number | null, checkbox_state: string, github_issue_number: number | null, github_issue_state: string | null, outcome_node_id: number | null, outcome_change_id: string | null, markdown_line_start: number | null, markdown_line_end: number | null, content_hash: string | null, created_at: string, updated_at: string, last_synced_at: string | null, };
